/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mock;

public class Sample {
    private Sub sub;

    public Sample() {}

    public Sample(Sub sub) {
        this.sub = sub;
    }

    public String pubGet() {
        return "pubGet";
    }

    public String pubGet(String suffix) {
        return pubGet() + suffix;
    }

    public String pubGetSubValue() {
        return sub.getValue();
    }

    public String pubGetStaticValue() {
        return Static.getValue();
    }

    public String pubGetValueWithPriGet(String suffix) {
        return priGet(suffix);
    }
    
    public void pubTrowsErr() throws Exception{
        priTrowsErr();
    }
    
    private String priGet() {
        return "priGet";
    }

    private void priTrowsErr() throws Exception{
        throw new Exception();
    }
    
    private String priGet(String suffix) {
        return priGet() + suffix;
    }

    public static class Sub {
        private String value;
        public Sub(String value) {
            this.value = value;
        }
        public String getValue() {
            return value;
        }
    }

    public static class Static {
        public static String getValue() {
            return "Static value";
        }
    }
}
