/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package any;

import org.junit.Test;

import lombok.AllArgsConstructor;
import lombok.Data;


public class ObjectToJsonTest {
    @Test public void test() {
    	User user = new User();
    }
    @Data
    private class User{
    	private String name;
    	private String sex;
    }
}
